import './assets/main.scss';
import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import router from './router/index';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import VueLuckWheel from '@lucky-canvas/vue';
import plugins from './utils/plugins';
var app = createApp(App);
app.use(plugins);
app.use(VueLuckWheel);
app.use(createPinia());
app.use(router);
app.use(ElementPlus);
app.mount('#app');
